nginx/njs

- test/test262
The skipped tests (which are expected to fail) are not executed in order to make output clearer.
> Test262: improved skipping of tests.

- src/njs_regexp.c
- src/test/njs_unit_test.c
With replacement containing "$'", "$\`" and Unicode characters.
The similar issue was fixed for String.prototype.replace() in 10127d70e941 (0.7.11).
Found by OSS-Fuzz.
> Fixed RegExp.prototype[@@replace]().

- test/fs/methods.t.js
> Fixed flaky fs tests

- src/njs_string.c
- src/test/njs_unit_test.c
Found by OSS-Fuzz and MemorySanitizer.
> Fixed open byte overread in decodeURI() and decodeURIComponent().

- src/njs_parser.c
- src/njs_parser.h
- src/test/njs_unit_test.c
This properly catches unsupported "await" in arguments.
This fixes #730 issue on Github.
> Fixed tracking of argument scope.

- nginx/ngx_js_shared_dict.c
After 5730d5f pool copy is not needed because
njs_vm_value_string_create() always create a copy.
>  Modules: removed extra copying in shared dictionary.

- nginx/ngx_http_js_module.c
- nginx/t/js_subrequests.t
Previously, when at least 2 subrequests were scheduled they both succeed, but the callback for the second threw an exception heap-use-after-free happened.
The issue was introduced in 0.8.1 (4cb8e873e8c6).
> HTTP: fixed r.subrequest() error handling.

- src/njs_utf8.h
- src/njs_value_conversion.h
When building by GCC with -O3 and -flto flags the following warning was reported:
src/njs_array.c: In function ‘njs_array_prototype_pop’: src/njs_array.c:1009:8: error: ‘length’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
1009 | if (length == 0) {
|     ^
Returning a specific code in njs_value_to_number() helps GCC to infer that there are only 2 return values are possible and both of them are handled.
> Fixed ‘length’ may be used in Array.prototype.pop().

- nginx/ngx_js.c
> Modules: adding NUL byte at the end of the module body.

- src/njs_error.c
- src/njs_number.c
- src/njs_string.c
- src/test/njs_unit_test.c
Ensuring that buf is always initialized in njs_throw_error_va() and njs_error_fmt_new(), by requiring fmt to always be non NULL.
This fixes GCC warnings like:
169 | njs_unicode_decode_t ctx;
| ^
In function ‘njs_utf8_length’,
inlined from ‘njs_error_new’ at src/njs_error.c:39:14,
inlined from ‘njs_throw_error_va’ at src/njs_error.c:69:5:
src/njs_utf8.h:141:12: error: ‘buf’ may be used uninitialized
[-Werror=maybe-uninitialized]
141 | return njs_utf8_stream_length(&ctx, p, len, 1, 1, NULL);
Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue using one of the [supported keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) here in this description (not in the …
> Fixed maybe-uninitialized warning in error creation.

- src/njs_builtin.c
- src/test/njs_unit_test.c
> Fixed "global" property handler.

- src/njs_function.c
- src/test/njs_unit_test.c
Fixed Function w/o args called relative an object.
> Fixed Function constructor handling when called without arguments.

- ts/ngx_core.d.ts
Correct the type definition for `NgxSharedDict.items()`. At runtime, I found out it returns an array of `[key, value]` objects, just like `Object.items()`. As documented here https://nginx.org/en/docs/njs/reference.html#dict_items
```
function dumpItems(r) {
ngx.shared.myarray.set("hello", "world")
console.log(ngx.shared.myarray.items()[0])
}
```
Console output
```
2024/07/30 12:14:42 [info] 22#22: *1 js: ['hello','world']
```
> fix(types): NgxKeyValuePair is actually an array

- nginx/ngx_http_js_module.c
- nginx/t/js_capture_variables.t
This PR exposes capture group variables like `$1`, `$2` to njs scripts in the `Request.variables` object, avoiding duplicate parsing to determine this value (on nginx side and on njs side).
I'm not very familiar with the testing framework of this project so I couldn't test everything, here's my test scenario though (it makes sure we handle limits correctly and ensures previous variables are still accessible).
<details>
<summary>Testing scenario</summary>
```javascript
// njs/test.js
function handler(r) {
for (let i = 0; i < 10; i++) {
console.log(`${i}: ${r.variables[i.toString()]}`);
}
console.log(`host: ${r.variables["http_host"]}`);
r.return(200, `OK ${r.variables.http_host}`);
}
export default {handler}
``` …
> feat(njs): expose capture group variables

- nginx/ngx_http_js_module.c
- nginx/ngx_js.h
- nginx/ngx_stream_js_module.c
- nginx/t/js_variables_nocache.t
- nginx/t/stream_js_variables_nocache.t
This commit adds support for an additional `nocache` flag in `js_set` directives. If set, the resulting nginx variable will have no_cacheable set to 1. This enables us to dynamically recompute a variable if the context changed (for example, in case of an internal redirection). It also gives some control over the phase when variables are computed without needing to explain phases in the docs: as the variable is not cached, it is recomputed every time it is needed. Advanced users needing to hack something to get a JS code to run at a certain point in the config can simply refer to a nocached js_set variable in the corresponding directives and it is guaranteed the variable getter will be called when this directive evaluates the variable.
Should they want to benefit from this without …
> feat(js_set): add nocache flag for uncacheable variables

- auto/expect
Configure: allow spaces in PATH.
This is useful for WSL (Windows Subsystem for Linux) where PATH by default contains spaces. 
> Configure: accept spaces in PATH.

- nginx/ngx_http_js_module.c
The issue was introduced in a14be61c86 (0.8.5).
This fixes #783 on Github.
> HTTP: fixed r.subrequest() check for nested subrequests.

- .github/workflows/check-pr.yml
GitHub is going to change the latest tag to point to 24.04 soon, so let's be proactive and pin to a specific version.
With that change, we'd also need to drop the _FORTIFY_SOURCE definition since it now has a stricter default on Ubuntu 24.04.
> CI: Run a check-pr job on a specific Ubuntu version.

- .github/workflows/check-pr.yml
- auto/quickjs
- external/qjs_fs_module.c
- nginx/config
- nginx/config.make
- nginx/ngx_http_js_module.c
- src/njs.h
- src/qjs.c
- src/qjs.h
- test/shell_test.exp
[QuickJS-NG](https://github.com/quickjs-ng/quickjs) is a fork of QuickJS which is actively developed.
> Added support for QuickJS-NG library.

- src/njs_parser.c
- src/njs_parser.h
- src/test/njs_unit_test.c
This fixes issue #836 on github.
> Add missed syntax error for await in template literal.

- nginx/ngx_http_js_module.c
- nginx/ngx_js.c
- nginx/ngx_js.h
- nginx/ngx_js_shared_dict.c
- nginx/ngx_stream_js_module.c
Prepared for QuickJS fetch support.
> QuickJS: making argument styles consistent in ngx_js.h.

- external/njs_shell.c
- external/qjs_query_string_module.c
- src/qjs.c
- src/qjs.h
Refactored out from qjs fetch patches.
> Fixed njs_qjs_object_completions().

- nginx/ngx_js.c
Fix the function to properly handler strings like "\0" which happens in tests. In js_fetch_objects.t:
```
for (var i = 0; i < 128; i++) {
var c = String.fromCodePoint(i);
```
Refactored out from qjs fetch patches.
> QuickJS: fixed ngx_qjs_string().

- external/qjs_query_string_module.c
- nginx/ngx_http_js_module.c
- src/qjs.c
No functional changes.
Refactored out from qjs fetch patches.
> QuickJS: calling njs_chb_destroy() in qjs_string_create_chb() internally.

- auto/quickjs
- src/qjs.c
In quickjs JS_AddIntrinsicBigInt() is moved from public API to JS_AddIntrinsicBaseObjects():
commit 6d6893bfa3d383d4952b67954003800aba1f4be8
Author: Fabrice Bellard <fabrice@bellard.org>
Date:   Wed Mar 19 12:33:54 2025 +0100
fixed BigInt hashing - removed -fno-bigint in qjsc and JS_AddIntrinsicBigInt() (BigInt is now considered as a base object)
> QuickJS: using JS_AddIntrinsicBigInt() if detected.

- nginx/ngx_js_shared_dict.c
See https://github.com/nginx/njs/pull/864#issuecomment-2746931068
> QuickJS: added missed JS_NewClass() for the SharedDictError class.

- src/qjs_buffer.c
JS_VALUE_GET_OBJ(v) was made hidden in 156d981.
> QuickJS: fixed compatibility with recent change in upstream.

- .github/workflows/check-pr.yml
- auto/quickjs
- external/qjs_query_string_module.c
- external/qjs_webcrypto_module.c
- external/qjs_xml_module.c
- nginx/ngx_http_js_module.c
- src/qjs.h
- src/qjs_buffer.c
> QuickJS: fixed compatibility issues with QuickJS-NG 0.9.0.

- test/options
mktemp: insufficient number of Xs in template `/tmp/njs_test.XXX'
> Test262: fixed mktemp format on OpenBSD.

- src/njs_regexp.c
- src/test/njs_unit_test.c
The issue was found by OSS-Fuzz. Segmentation fault at the input:
' a'.split(/|()/)
Actually that is old issue: previously (before removing short_strings in  https://github.com/nginx/njs/pull/848) to obtain value of captured group was used njs_string_prop() without check for its value argument type and it by mistake converted undefined value to empty string, while there is expected undefined value itself. After removing short_strings, njs_string prop() throws segmentation fault.
> Fixed regexp undefined value of captured group.

- nginx/t/js_body_filter.t
The 1496ed3f commit made visible a problem with the fragile filter tests which depend on the exact sequence of data chunks. The fix is to use perl http server to ensure the order.
> Tests: fixed js_body_filter.t.

- external/qjs_query_string_module.c
- src/njs_sprintf.c
- src/njs_string.c
- src/njs_string.h
- src/qjs_buffer.c
In file included from src/njs_main.h:48,
from src/njs_diyfp.c:12:
src/njs_string.h: In function ‘njs_string_encode’: src/njs_string.h:229:36: error: initializer-string for array of ‘unsigned char’
truncates NUL terminator but destination lacks ‘nonstring’ attribute (
17 chars into 16 available) [-Werror=unterminated-string-initialization]
229 |     static const u_char  hex[16] = "0123456789ABCDEF";
> Fixed GCC 15 build with -Wunterminated-string-initialization.

- src/njs.h
ngx_http_js_module.c:936:22: error: initializer-string for array of ‘char’ truncates NUL terminator
but destination lacks ‘nonstring’ attribute (16 chars into 15 available) [-Werror=unterminated-string-initialization]
936 |             .value = "PeriodicSession",
|                      ^~~~~~~~~~~~~~~~~
> HTTP: fixed GCC 15 build with -Wunterminated-string-initialization.

- src/njs_promise.c
Hi! 
I'm experimenting with memory pool limits for NJS and I've spotted 2 places where the result of
`njs_promise_create_function` call is dereferenced without proper checks. Causing segmentation fault on nullptr dereference.
I'm not able to share minimal example -- it's hard to hit precisely these two lines via memory allocation failure.
> Add missing null checks for njs_promise_create_function allocations

- nginx/ngx_http_js_module.c
- nginx/ngx_js.h
- nginx/ngx_js_shared_dict.c
- nginx/ngx_js_shared_dict.h
- nginx/ngx_stream_js_module.c
- nginx/t/js_fetch.t
- nginx/t/js_fetch_https.t
- nginx/t/js_fetch_objects.t
- nginx/t/js_fetch_resolver.t
- nginx/t/js_fetch_timeout.t
- nginx/t/js_fetch_verify.t
- nginx/t/js_periodic_fetch.t
- nginx/t/js_shared_dict.t
- nginx/t/js_shared_dict_state.t
- nginx/t/stream_js_fetch.t
- nginx/t/stream_js_fetch_https.t
- nginx/t/stream_js_fetch_init.t
- nginx/t/stream_js_periodic_fetch.t
- nginx/t/stream_js_shared_dict.t
- nginx/t/stream_js_shared_dict_state.t
- src/njs_chb.c
Modules: added state file for a shared dictionary.
A new optional state parameter is added for js_shared_dict_zone
directive. state parameter specifies a file that keeps the current state
of the shared dict in the JSON format and makes it persistent
across nginx restarts.
This closes https://github.com/nginx/njs/issues/709 feature request on Github.
> Shared dict state file

- src/njs_function.c
- src/test/njs_unit_test.c
The Function constructor uses a `(function(<args>) {<body>})` template to construct new functions. This approach was vulnerable to template injection where malicious code could close the function body early and ignore the trailing brackets using // comments.
The fix is to insert extra newlines into the template, which prevents // comments from commenting out the remaining template.
This fixes issue #921.
> Fixed Function constructor template injection.

- nginx/ngx_js.c
Already defined in ngx_files.h (included from ngx_core.h).
> Removed NGX_MAX_PATH define.

- nginx/ngx_http_js_module.c
- nginx/t/js_internal_redirect.t
Previously, when processing requests with `If-Match` and `If-Unmodified-Since` headers worker process crashed.
For example with the following code:
try { r.return(200) }
catch (e) { r.internalRedirect() }
The fix is to disable not_modified filter as it was done in nginx perl module nginx/nginx@d9887ee2.
> Fixed NULL pointer dereference when processing If-* headers.

- src/njs_vm.h
- src/test/njs_unit_test.c
This change allows EarleyBoyer benchmark from
arewefastyet/benchmarks/v8-v7 to pass with default settings.
Previous commit 5e9a6d5 (v0.7.9) reduced the stack size to prevent stack overflow when compiling with -O0 in computed goto mode, where native stack frames for njs_vmcode_interpreter() consume ~80KB each. To address this, we now set a lower maximum stack size specifically for unit tests.
This fixes #939 issue on Github.
> Change: increasing the default stack size to 160k.

- auto/quickjs
- nginx/config
- src/qjs.h
checking for QuickJS library -lquickjs In file included from build/autotest.c:6:
/home/xeioex/workspace/nginx/nginScript/quickjs/quickjs.h:1052:34: error: cast from 'JSCFunctionMagic *' (aka 'struct JSValue (*)(struct JSContext *, struct JSValue, int, struct JSValue *, int)') to 'JSCFunction *' (aka 'struct JSValue (*)(struct JSContext *, struct JSValue, int, struct JSValue *)') converts to incompatible function type [-Werror,-Wcast-function-type-mismatch] 1052 | return JS_NewCFunction2(ctx, (JSCFunction *)func, name, length, cproto, magic);
-Wcast-function-type-mismatch become enabled by -Werror since clang 19.
> Fixed building QuickJS support with clang 19.
